### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by hndanesh** [jcabi/jcabi-aspects#110]
I'm just getting started with this project. Can someone tell me why the tests are failing?

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.jcabi.aspects.aj.MnemosTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.148 sec - in com.jcabi.aspects.aj.MnemosTest
Running com.jcabi.aspects.UnitedThrowTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.465 sec - in com.jcabi.aspects.UnitedThrowTest
Running com.jcabi.aspects.aj.RepeaterTest
[DEBUG] pool-1-thread-2 com.jcabi.aspects.aj.ImmutabilityChecker: #check(class com.jcabi.aspects.aj.Repeater): immutability checked
[WARN] pool-1-thread-2 com.jcabi.aspects.aj.RepeaterTest$3: #call(): attempt #1/3 failed with java.lang.ArrayIndexOutOfBoundsException in 78µs (92µs in total): null
[WARN] pool-1-thread-2 com.jcabi.aspects.aj.RepeaterTest$3: #call(): attempt #2/3 failed with java.lang.ArrayIndexOutOfBoundsException in 93µs (190ms in total): null
[WARN] pool-1-thread-6 com.jcabi.aspects.aj.RepeaterTest$1: #call(): attempt #1/3 failed with java.lang.IllegalStateException in 1ms (1ms in total): null
[WARN] pool-1-thread-6 com.jcabi.aspects.aj.RepeaterTest$1: #call(): attempt #2/3 failed with java.lang.IllegalStateException in 106µs (143ms in total): null
[WARN] pool-1-thread-7 com.jcabi.aspects.aj.RepeaterTest$2: #call(): attempt #1/3 failed with java.lang.IllegalStateException in 90µs (107µs in total): null
[WARN] pool-1-thread-7 com.jcabi.aspects.aj.RepeaterTest$2: #call(): attempt #2/3 failed with java.lang.IllegalStateException in 49µs (41ms in total): null
[WARN] pool-1-thread-7 com.jcabi.aspects.aj.RepeaterTest$2: #call(): attempt #3/3 failed with java.lang.IllegalStateException in 101µs (292ms in total): null
[WARN] pool-1-thread-5 com.jcabi.aspects.aj.RepeaterTest$5: #call(): attempt #1/3 failed with java.lang.ArrayIndexOutOfBoundsException in 76µs (91µs in total): null
[WARN] pool-1-thread-5 com.jcabi.aspects.aj.RepeaterTest$5: #call(): attempt #2/3 failed with java.lang.ArrayIndexOutOfBoundsException in 82µs (140ms in total): null
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.925 sec - in com.jcabi.aspects.aj.RepeaterTest
Running com.jcabi.aspects.aj.ImmutabilityCheckerTest
[DEBUG] pool-1-thread-6 com.jcabi.aspects.aj.ImmutabilityChecker: #check(class com.jcabi.aspects.aj.ImmutabilityCheckerTest$Recursive): immutability checked
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in com.jcabi.aspects.aj.ImmutabilityCheckerTest
Running com.jcabi.aspects.LoggableTest
[INFO] pool-1-thread-6 com.jcabi.aspects.LoggableTest$Foo: some text#last('TEST'): 'T' in 588.48µs
[DEBUG] pool-1-thread-5 com.jcabi.aspects.LoggableTest$Foo: #text(): entered
[WARN] pool-1-thread-5 com.jcabi.aspects.LoggableTest$Foo: #text(): 'some static text' in 2.01s (too slow!)
[INFO] pool-1-thread-7 com.jcabi.aspects.aj.NamedThreads: jcabi-aspects 1.0-SNAPSHOT/df931c3 started new daemon thread jcabi-timeable for interrupting of @Timeable annotated methods
[INFO] pool-1-thread-7 com.jcabi.aspects.LoggableTest$Foo: #revert('hello'): 'olleh' in 2.64ms
[INFO] pool-1-thread-2 com.jcabi.aspects.aj.NamedThreads: jcabi-aspects 1.0-SNAPSHOT/df931c3 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[DEBUG] pool-1-thread-2 test-logger: #explicitLoggerName(): entered
[DEBUG] pool-1-thread-2 test-logger: #explicitLoggerName(): 'some static text' in 5.17ms
[DEBUG] jcabi-loggable com.jcabi.aspects.aj.MethodLogger$2: Logging monitor thread interrupted
[INFO] pool-1-thread-4 com.jcabi.aspects.LoggableTest$Foo: #logsDurationInSeconds(): 'some static text' in 2.000s
[INFO] pool-1-thread-7 com.jcabi.aspects.LoggableTest$Foo: #self(): 'some text' in 40.72µs
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.563 sec - in com.jcabi.aspects.LoggableTest
Running com.jcabi.aspects.aj.ParallelizerTest
[DEBUG] pool-1-thread-7 com.jcabi.aspects.aj.ImmutabilityChecker: #check(class com.jcabi.aspects.aj.Parallelizer): immutability checked
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.053 sec - in com.jcabi.aspects.aj.ParallelizerTest
Running com.jcabi.aspects.RetryOnFailureTest
[WARN] pool-1-thread-1 com.jcabi.aspects.RetryOnFailureTest$1: #run(): attempt #1/3 failed with java.lang.IllegalArgumentException in 90µs (104µs in total): this exception should be caught and swallowed
[WARN] pool-1-thread-2 com.jcabi.aspects.RetryOnFailureTest$2: #run(): attempt #1/3 failed with java.lang.AssertionError in 194µs (207µs in total): Should be caught and ignored.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.028 sec - in com.jcabi.aspects.RetryOnFailureTest
Running com.jcabi.aspects.ScheduleWithFixedDelayTest
SLF4J: The following loggers will not work because they were created
SLF4J: during the default configuration phase of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: com.jcabi.aspects.aj.ImmutabilityChecker
SLF4J: com.jcabi.aspects.ScheduleWithFixedDelayTest$LongDelaySample
SLF4J: com.jcabi.aspects.ScheduleWithFixedDelayTest$LongDelaySample
[INFO] pool-1-thread-3 com.jcabi.aspects.ScheduleWithFixedDelayTest$Sample: scheduled for execution with 1 MILLISECONDS interval
[INFO] pool-1-thread-3 com.jcabi.aspects.ScheduleWithFixedDelayTest$Sample: execution stopped after 2s and 800 tick(s)
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.334 sec - in com.jcabi.aspects.ScheduleWithFixedDelayTest
Running com.jcabi.aspects.ImmutableTest
[DEBUG] pool-1-thread-7 com.jcabi.aspects.aj.ImmutabilityChecker: #check(class [Ljava.lang.String;): immutability checked
[DEBUG] pool-1-thread-7 com.jcabi.aspects.aj.ImmutabilityChecker: #check(interface com.jcabi.aspects.ImmutableTest$ImmutableInterface): immutability checked
[DEBUG] pool-1-thread-7 com.jcabi.aspects.aj.ImmutabilityChecker: #check(class com.jcabi.aspects.ImmutableTest$TruelyImmutable): immutability checked
[DEBUG] pool-1-thread-1 com.jcabi.aspects.aj.ImmutabilityChecker: #check(class com.jcabi.aspects.ImmutableTest$TruelyImmutableWithNonPrivateFields): immutability checked
[DEBUG] pool-1-thread-1 com.jcabi.aspects.aj.ImmutabilityChecker: #check(class [I): immutability checked
Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.135 sec - in com.jcabi.aspects.ImmutableTest
Running com.jcabi.aspects.TimeableTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.885 sec - in com.jcabi.aspects.TimeableTest
Running com.jcabi.aspects.JSR303Test
[INFO] pool-1-thread-3 com.jcabi.aspects.JSR303Test$Foo: #voidAlways(): in 491.51ms
[ERROR] pool-1-thread-2 com.jcabi.aspects.JSR303Test$Foo: #foo('some text'): thrown javax.validation.ConstraintViolationException({javax.validation.constraints.Pattern.message}) out of com.jcabi.aspects.aj.MethodValidator#validate[181] in 510ms
[ERROR] pool-1-thread-4 com.jcabi.aspects.JSR303Test$Foo: #nullValue(): thrown javax.validation.ConstraintViolationException({javax.validation.constraints.NotNull.message}) out of com.jcabi.aspects.aj.MethodValidator#after[146] in 484ms
[INFO] pool-1-thread-5 com.jcabi.aspects.aj.MethodValidator: JSR-303 validator org.hibernate.validator.internal.engine.ValidatorImpl instantiated by jcabi-aspects 1.0-SNAPSHOT/df931c3
[INFO] pool-1-thread-4 com.jcabi.aspects.JSR303Test$Foo: #foo('123'): -1 in 13.22ms
[ERROR] pool-1-thread-8 com.jcabi.aspects.JSR303Test$Foo: #foo(NULL): thrown javax.validation.ConstraintViolationException({javax.validation.constraints.NotNull.message}) out of com.jcabi.aspects.aj.MethodValidator#validate[181] in 11ms
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.568 sec - in com.jcabi.aspects.JSR303Test
Running com.jcabi.aspects.aj.QuietExceptionsLoggerTest
[DEBUG] pool-1-thread-8 com.jcabi.aspects.aj.ImmutabilityChecker: #check(class com.jcabi.aspects.aj.QuietExceptionsLogger): immutability checked
[WARN] pool-1-thread-4 java.lang.Object: java.lang.Exception
    at com.jcabi.aspects.aj.QuietExceptionsLogger.wrap(QuietExceptionsLogger.java:82)
    at com.jcabi.aspects.aj.QuietExceptionsLoggerTest.exception(QuietExceptionsLoggerTest.java:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.417 sec - in com.jcabi.aspects.aj.QuietExceptionsLoggerTest
Running com.jcabi.aspects.CacheableTest
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5400173087835387085' in 168.60µs
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5400173087835387085' cached in 11ms, valid forever
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #get(): 5400173087835387085 in 60.55µs
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5400173087835387085' from cache (hit #1, 22ms old)
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #get(): 5400173087835387085 cached in 23ms, valid for 1s
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5400173087835387085' from cache (hit #2, 24ms old)
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5400173087835387085' from cache (hit #3, 25ms old)
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #get(): 5400173087835387085 from cache (hit #1, 39ms old)
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5400173087835387085' from cache (hit #4, 26ms old)
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5400173087835387085' from cache (hit #5, 31ms old)
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #flush(): #get():5400173087835387085 removed from cache before the call
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5816123479977659477' in 30.45µs
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5816123479977659477' cached in 2ms, valid forever
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #get(): 5816123479977659477 in 30.87µs
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5816123479977659477' from cache (hit #1, 4ms old)
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #get(): 5816123479977659477 cached in 5ms, valid for 1s
[DEBUG] pool-1-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '5816123479977659477' from cache (hit #2, 5ms old)
[DEBUG] pool-2-thread-1 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' in 31.08µs
[DEBUG] pool-2-thread-1 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' cached in 2ms, valid forever
[DEBUG] pool-2-thread-1 com.jcabi.aspects.CacheableTest$Foo: #get(): 689614735858032066 in 33.94µs
[DEBUG] pool-2-thread-1 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #1, 9ms old)
[DEBUG] pool-2-thread-1 com.jcabi.aspects.CacheableTest$Foo: #get(): 689614735858032066 cached in 9ms, valid for 1s
[DEBUG] pool-2-thread-1 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #2, 10ms old)
[DEBUG] pool-2-thread-2 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #3, 16ms old)
[DEBUG] pool-2-thread-2 com.jcabi.aspects.CacheableTest$Foo: #get(): 689614735858032066 from cache (hit #1, 17ms old)
[DEBUG] pool-2-thread-2 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #4, 18ms old)
[DEBUG] pool-2-thread-3 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #5, 19ms old)
[DEBUG] pool-2-thread-3 com.jcabi.aspects.CacheableTest$Foo: #get(): 689614735858032066 from cache (hit #2, 19ms old)
[DEBUG] pool-2-thread-3 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #6, 20ms old)
[DEBUG] pool-2-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #7, 21ms old)
[DEBUG] pool-2-thread-4 com.jcabi.aspects.CacheableTest$Foo: #get(): 689614735858032066 from cache (hit #3, 21ms old)
[DEBUG] pool-2-thread-4 com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #8, 23ms old)
[ERROR] Thread-29 com.jcabi.aspects.CacheableTest$Foo: #never(): thrown java.lang.IllegalStateException(java.lang.InterruptedException: sleep interrupted) out of com.jcabi.aspects.CacheableTest$Foo#never_aroundBody8[198] in 30ms
Exception in thread "Thread-29" java.lang.IllegalStateException: java.lang.InterruptedException: sleep interrupted  at com.jcabi.aspects.CacheableTest$Foo.never_aroundBody8(CacheableTest.java:198)    at com.jcabi.aspects.CacheableTest$Foo$AjcClosure9.run(CacheableTest.java:1)    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)   at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)  at com.jcabi.aspects.CacheableTest$Foo.never_aroundBody10(CacheableTest.java:194)   at com.jcabi.aspects.CacheableTest$Foo$AjcClosure11.run(CacheableTest.java:1)   at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)    at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)  at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)at com.jcabi.aspects.CacheableTest$Foo.never(CacheableTest.java:194)   at com.jcabi.aspects.CacheableTest$1.run(CacheableTest.java:113)    at java.lang.Thread.run(Thread.java:745)Caused by: java.lang.InterruptedException: sleep interrupted    at java.lang.Thread.sleep(Native Method)    at java.lang.Thread.sleep(Thread.java:340)  at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)   at com.jcabi.aspects.CacheableTest$Foo.never_aroundBody8(CacheableTest.java:196)    ... 13 more[INFO] pool-1-thread-5 com.jcabi.aspects.aj.NamedThreads: jcabi-aspects 1.0-SNAPSHOT/df931c3 started new daemon thread jcabi-cacheable for automated cleaning of expired @Cacheable values
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #toString(): '2012794429156900896' in 36.11µs
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #toString(): '2012794429156900896' cached in 1ms, valid forever
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #get(): 2012794429156900896 in 25.07µs
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #toString(): '2012794429156900896' from cache (hit #1, 11ms old)
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #get(): 2012794429156900896 cached in 11ms, valid for 1s
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #toString(): '2012794429156900896' from cache (hit #2, 12ms old)
[DEBUG] jcabi-cacheable com.jcabi.aspects.CacheableTest$Foo: #toString(): '5816123479977659477' from cache (hit #3, 2s old)
[DEBUG] jcabi-cacheable com.jcabi.aspects.aj.MethodCacher: #get():5816123479977659477 expired in cache
[DEBUG] jcabi-cacheable com.jcabi.aspects.CacheableTest$Foo: #toString(): '689614735858032066' from cache (hit #9, 2s old)
[DEBUG] jcabi-cacheable com.jcabi.aspects.aj.MethodCacher: #get():689614735858032066 expired in cache
[DEBUG] jcabi-cacheable com.jcabi.aspects.CacheableTest$Foo: #toString(): '2012794429156900896' from cache (hit #3, 2s old)
[DEBUG] jcabi-cacheable com.jcabi.aspects.aj.MethodCacher: #get():2012794429156900896 expired in cache
[DEBUG] jcabi-cacheable com.jcabi.aspects.aj.MethodCacher: #staticGet():'-9094191193162593807' expired in cache
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #toString(): '-7245010933477855256' in 43.30µs
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #toString(): '-7245010933477855256' cached in 2ms, valid forever
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #get(): -7245010933477855256 in 47.77µs
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #toString(): '-7245010933477855256' from cache (hit #1, 5ms old)
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #get(): -7245010933477855256 cached in 6ms, valid for 1s
[DEBUG] pool-1-thread-5 com.jcabi.aspects.CacheableTest$Foo: #toString(): '-7245010933477855256' from cache (hit #2, 7ms old)
[DEBUG] pool-1-thread-6 com.jcabi.aspects.CacheableTest$Foo: #staticGet(): '-6222350667433641094' cached in 1ms, valid for 1s
[DEBUG] pool-1-thread-6 com.jcabi.aspects.CacheableTest$Foo: #staticGet(): '-6222350667433641094' from cache (hit #1, 17ms old)
[DEBUG] pool-1-thread-6 com.jcabi.aspects.CacheableTest$Foo: #staticFlush(): #staticGet():'-6222350667433641094' removed from cache before the call
[DEBUG] pool-1-thread-6 com.jcabi.aspects.CacheableTest$Foo: #staticGet(): '-9094191193162593807' cached in 1ms, valid for 1s
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.214 sec - in com.jcabi.aspects.CacheableTest
Running com.jcabi.aspects.AsyncTest
[INFO] pool-1-thread-6 com.jcabi.aspects.aj.NamedThreads: jcabi-aspects 1.0-SNAPSHOT/df931c3 started new daemon thread jcabi-async for Asynchronous method execution
[INFO] pool-1-thread-1 com.jcabi.aspects.aj.NamedThreads: jcabi-aspects 1.0-SNAPSHOT/df931c3 started new daemon thread jcabi-async for Asynchronous method execution
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.103 sec <<< FAILURE! - in com.jcabi.aspects.AsyncTest
throwsWhenMethodDoesNotReturnVoidOrFuture(com.jcabi.aspects.AsyncTest)  Time elapsed: 0.035 sec  <<< ERROR!
java.lang.IllegalStateException: #asyncMethodThatReturnsInt(...): Return type is int, not void or Future, cannot use @Async
    at com.jcabi.aspects.aj.MethodAsyncRunner.wrap(MethodAsyncRunner.java:86)
    at com.jcabi.aspects.AsyncTest$Foo.asyncMethodThatReturnsInt(AsyncTest.java:139)
    at com.jcabi.aspects.AsyncTest.throwsWhenMethodDoesNotReturnVoidOrFuture(AsyncTest.java:96)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Running com.jcabi.aspects.aj.MethodSchedulerTest
[INFO] pool-1-thread-2 com.jcabi.aspects.aj.MethodSchedulerTest$LongRun: scheduled for execution with 1 NANOSECONDS interval
[INFO] pool-1-thread-2 com.jcabi.aspects.aj.MethodSchedulerTest$LongRun: execution stopped after 10ms and 0 tick(s)
[INFO] pool-1-thread-7 com.jcabi.aspects.aj.MethodSchedulerTest$ShortRun: scheduled for execution with 1 NANOSECONDS interval
[INFO] pool-1-thread-7 com.jcabi.aspects.aj.MethodSchedulerTest$ShortRun: execution stopped after 5s and 5 tick(s)
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.035 sec - in com.jcabi.aspects.aj.MethodSchedulerTest

Results :

Tests in error: 
  AsyncTest.throwsWhenMethodDoesNotReturnVoidOrFuture:96 » IllegalState #asyncMe...

Tests run: 55, Failures: 0, Errors: 1, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.100 s
[INFO] Finished at: 2014-12-14T21:14:16+11:00
[INFO] Final Memory: 22M/173M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project jcabi-aspects: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/hossein/dev/src/jcabi-aspects/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by oruam85** [comment]
@hndanesh @yegor256 yesterday  i had a similar problem in this project. you can solve it deleting the .m2 folder and run `mvn clean install -Pqulice` again.

This can take 45 min.
