### ISSUE TITLE
ImmutabilityChecker is broken

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-aspects#128]
```
java.lang.IllegalArgumentException: Can not set final java.lang.String field com.jcabi.urn.URN.uri to com.netbout.mock.MkUser
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:164)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:168)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:55)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.lang.reflect.Field.get(Field.java:379)
	at com.jcabi.aspects.aj.ImmutabilityChecker.checkDeclaredAndActualTypes(ImmutabilityChecker.java:232)
	at com.jcabi.aspects.aj.ImmutabilityChecker.fields(ImmutabilityChecker.java:195)
	at com.jcabi.aspects.aj.ImmutabilityChecker.check(ImmutabilityChecker.java:114)
	at com.jcabi.aspects.aj.ImmutabilityChecker.checkDeclaredAndActualTypes(ImmutabilityChecker.java:225)
	at com.jcabi.aspects.aj.ImmutabilityChecker.fields(ImmutabilityChecker.java:195)
	at com.jcabi.aspects.aj.ImmutabilityChecker.check(ImmutabilityChecker.java:114)
	at com.jcabi.aspects.aj.ImmutabilityChecker.after(ImmutabilityChecker.java:72)
	at com.netbout.mock.MkUser.<init>(MkUser.java:78)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.4`

**Comment by dmarkov** [comment]
once `128-1ba0b794` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by dmarkov** [comment]
the last puzzle `128-1ba0b794`/#131 solved
