### ISSUE TITLE
Error: java.lang.UnsatisfiedLinkError: android.util.Log.isLoggable(Ljava/lang/String;I)

### ISSUE THREAD

**Issue by jkamaraj** [jcabi/jcabi-aspects#153]
Hi Team,

I am trying to use jcabi and slf4j to log all the Android methods in my code but it fails with the below error.
Not sure whether it is a bug or my mistake? 
====================================================================

org.aspectj.lang.NoAspectBoundException: Exception while initializing com.jcabi.aspects.aj.MethodLogger: java.lang.UnsatisfiedLinkError: android.util.Log.isLoggable(Ljava/lang/String;I)Z
        at android.util.Log.isLoggable(Native Method)
        at org.slf4j.impl.AndroidLoggerAdapter.isLoggable(AndroidLoggerAdapter.java:544)
        at org.slf4j.impl.AndroidLoggerAdapter.isInfoEnabled(AndroidLoggerAdapter.java:272)
        at com.jcabi.log.Logger.isInfoEnabled(Logger.java:271)
        at com.jcabi.log.Logger.info(Logger.java:192)
        at com.jcabi.aspects.aj.NamedThreads.newThread(NamedThreads.java:79)
        at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:610)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:924)
        at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1590)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:333)
        at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:594)
        at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:698)
        at com.jcabi.aspects.aj.MethodLogger.<init>(MethodLogger.java:86)
        at com.jcabi.aspects.aj.MethodLogger.ajc$postClinit(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.<clinit>(MethodLogger.java:1)
        at com.gazolinia.test.TestURLBuilder.getResourcesEndPoint(TestURLBuilder.java)

Thanks,
Jai

**Comment by jkamaraj** [comment]
My pom.xml entries.

    
    <dependency>
      <groupId>com.jcabi</groupId>
      <artifactId>jcabi-aspects</artifactId>
      <version>LATEST</version>
    </dependency>
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjrt</artifactId>
      <version>LATEST</version>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-android</artifactId>
        <version>1.7.6</version>
    </dependency>

      
      <plugin>
        <groupId>com.jcabi</groupId>
        <artifactId>jcabi-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>ajc</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@jkamaraj I don't know what is that... seems to be a problem with SLF4J and Android logging integration. it's outside of scope of jcabi-aspects..
