### ISSUE TITLE
jcabi pom dependency issue

### ISSUE THREAD

**Issue by PalakArora** [jcabi/jcabi-aspects#177]
Hi, 

I have done the following configuration in pom.xml for jcabi

               <dependency>
			<groupId>com.jcabi</groupId>
			<artifactId>jcabi-aspects</artifactId>
			<version>0.12</version>
		</dependency>
  	   	<dependency>
     	 	<groupId>org.aspectj</groupId>
     	 	<artifactId>aspectjrt</artifactId>
     	 	<version>1.7.3</version>
   	 	</dependency>
   	 	<dependency>
 			<groupId>c3p0</groupId>
 			<artifactId>c3p0</artifactId>
	    	<version>0.9.1.2</version> 
		</dependency>

             <pluginManagement>
  			<plugins>
   				 <plugin>
      					<groupId>org.eclipse.m2e</groupId>
      					<artifactId>lifecycle-mapping</artifactId>
    				    <version>1.0.0</version>
      					<configuration>
       				  	  <lifecycleMappingMetadata>
         			   	 	<pluginExecutions>
            					<pluginExecution>
             							 <pluginExecutionFilter>
              									  	<groupId>com.jcabi</groupId>
                									<artifactId>jcabi-maven-plugin</artifactId>
                									<versionRange>[0.0,)</versionRange>
                									<goals>
                  											<goal>ajc</goal>
                									</goals>
              							</pluginExecutionFilter>
             							 <action>
             				  				 <execute />
             							 </action>
            					</pluginExecution>
         					</pluginExecutions>
       				   </lifecycleMappingMetadata>
      			</configuration>
   		 		</plugin>
  			</plugins>
		</pluginManagement>

              <plugin>
        	<groupId>com.jcabi</groupId>
       		    <artifactId>jcabi-maven-plugin</artifactId>
        		<executions>
         		 	<execution>
           				 <goals>
             				 <goal>ajc</goal>
           				 </goals>
          			</execution>
        		</executions>
      	   </plugin>

And i am trying to build my application on apache tomact 7. I get the following error while starting the server:
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean#0': Invocation of init method failed; nested exception is java.lang.AbstractMethodError: org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultParameterNameProvider()Ljavax/validation/ParameterNameProvider;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AbstractMethodError: org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultParameterNameProvider()Ljavax/validation/ParameterNameProvider;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:202)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:187)
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.configureParameterNameProviderIfPossible(LocalValidatorFactoryBean.java:276)
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:245)
	at org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean.afterPropertiesSet(OptionalValidatorFactoryBean.java:40)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1625)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
	... 21 more

Please help @yegor256

**Comment by yegor256** [comment]
@PalakArora why do you think the exception is related to jcabi-aspects?

**Comment by PalakArora** [comment]
@yegor256 as soon as i add the following dependency:
<dependency>
			<groupId>com.jcabi</groupId>
			<artifactId>jcabi-aspects</artifactId>
			<version>0.12</version>
		</dependency>

the error starts appearing

**Comment by yegor256** [comment]
@PalakArora try to exclude `javax.validation:validation-api` from `com.jcabi:jcabi-aspects`

**Comment by PalakArora** [comment]
If i exclude the dependency. MethodLogger class gives error

Exception in thread "main" org.aspectj.lang.NoAspectBoundException: Exception while initializing com.jcabi.aspects.aj.MethodLogger: java.lang.NoClassDefFoundError: javax/validation/ValidationException
	at com.jcabi.aspects.aj.MethodLogger.aspectOf(MethodLogger.java:1)
	at com.ev.p2p.logback.QueueProducer.main(QueueProducer.java:17)
Caused by: java.lang.NoClassDefFoundError: javax/validation/ValidationException
	at com.jcabi.log.VerboseRunnable.<init>(VerboseRunnable.java:88)
	at com.jcabi.aspects.aj.MethodLogger.<init>(MethodLogger.java:90)
	at com.jcabi.aspects.aj.MethodLogger.ajc$postClinit(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.<clinit>(MethodLogger.java:1)
	at com.ev.p2p.logback.QueueProducer.main(QueueProducer.java)
Caused by: java.lang.ClassNotFoundException: javax.validation.ValidationException
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more

**Comment by PalakArora** [comment]
@yegor256 Please refer to the above comment

**Comment by yegor256** [comment]
@PalakArora you need to have that validation-api dependency in classpath, but there is a conflict between the one provided by Spring and the one inside jcabi-aspects. check what you have in classpath, using `mvn dependency:tree`

**Comment by Cervator** [comment]
I just hit what appears to be this issue as well. Am using a fairly typical Spring application.

I have `javax.validation:validation-api` on jcabi and hibernate as well with `org.hibernate:hibernate-validator` but unfortunately at the exact same version level. I tried excluding it anyway:

```xml
    <dependency>
      <groupId>com.jcabi</groupId>
      <artifactId>jcabi-aspects</artifactId>
      <version>0.22</version>
      <exclusions>
        <exclusion>
          <groupId>javax.validation</groupId>
          <artifactId>validation-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

And the dependency tree only has it once now, as expected. But the error didn't change:

```
Caused by: javax.validation.ValidationException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
```

Admittedly the wording is slightly different, but they both occur as Spring is trying to set up Hibernate. Could it be some sort of conflict between jcabi's use of AspectJ and Spring AOP?

It doesn't seem to matter if I have any actual `@Loggable` attached to anything, and that doesn't seem like it is resulting in any weaving anyway, I always get:

```
[INFO] --- jcabi-maven-plugin:0.13.2:ajc (default) @ citeweb-ui ---
[INFO] jcabi-aspects 0.18/55a5c13 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[INFO] jcabi-aspects 0.18/55a5c13 started new daemon thread jcabi-cacheable for automated cleaning of expired @Cacheable values

21 warnings
[INFO] ajc result: 13 file(s) processed, 0 pointcut(s) woven, 0 error(s), 0 warning(s)
```

Those 21 warnings made me wonder so I ran Maven with debug on. That didn't tell me anything of interest although it did point out that a separate log file existed (target/jcabi-ajc.log). In there I found some details but am not sure how helpful those will be. I tried to make a new dummy class in my project to try to limit any effect from Spring, but same story. Snippet from the detail log:

```
\Dummy.java:7 [warning] can not implement lazyTjp on this joinpoint method-execution(void Dummy.myMethod(java.lang.String)) because around advice is used [Xlint:canNotImplementLazyTjp]
	
	see also: C:\Users\Cervator\.m2\repository\com\jcabi\jcabi-aspects\0.22\jcabi-aspects-0.22.jar!com\jcabi\aspects\aj\MethodLogger.class::0
Join point 'method-execution(void Dummy.myMethod(java.lang.String))' in Type 'Dummy' (Dummy.java:7) advised by around advice from 'com.jcabi.aspects.aj.MethodLogger' (jcabi-aspects-0.22.jar!MethodLogger.class(from MethodLogger.java))
```

Does all that help any? In case it matters my app is on Spring 3.1.0

**Comment by Cervator** [comment]
Oho! I dug a little deeper and found #102 which looks to be just a logged error with no impact, but matches the error message more exactly. That led me to the qulice fix of adding `hibernate-validator` as a plugin dependency, although to `jcabi-maven-plugin` rather than the qulice thing. So now I've got:

```xml
      <plugin>
        <groupId>com.jcabi</groupId>
        <artifactId>jcabi-maven-plugin</artifactId>
        <version>0.13.2</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>ajc</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>1.8.3</version>
          </dependency>
          <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjtools</artifactId>
            <version>1.8.3</version>
          </dependency>
          <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>5.0.1.Final</version>
            <scope>runtime</scope>
          </dependency>
        </dependencies>
      </plugin>
```

And it looks like it works!

```
MainController #doLogin(NULL, NULL, {}, org.mortbay.jetty.servlet.HashSessionManager$Session:a8g34pdiqbmy18lv1n869ke4h@1089853261): 'login' in 173.55µs
```

Although I'm not sure if this matters (comes immediately after):

```
DEBUG [jcabi-loggable]  com.jcabi.aspects.aj.MethodLogger$2 Logging monitor thread interrupted
```

Being that it is just debug I won't worry too much, nor lose sleep over why I had to add `hibernate-validator` lest my Spring app would fail to start :-)

I can play with it some more now, yay! Thanks for the great utility.

Maybe this could help in @PalakArora's situation as well? Ping!
