### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in MethodLogger

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-aspects#223]
```
java.lang.ArrayIndexOutOfBoundsException: 0 
  at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:229)
  at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
  at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.5`

**Comment by Anand093** [comment]
mvn install gives error 

[ERROR] 12095
java.lang.ArrayIndexOutOfBoundsException: 12095
	at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2502)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseEpilog(MXParser.java:1604)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1434)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3856)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:109)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:82)

**Comment by Anand093** [comment]
Its blocker for me to generate zip file, plz help me on this
