### ISSUE TITLE
javax.validation.ConstraintViolationException: may not be null for a mocked object in TestNG test

### ISSUE THREAD

**Issue by sandeepkhanzode** [jcabi/jcabi-aspects#234]
I started to integrate jcabi-aspects into an already built Spring application with JSR-303 Hibernate-Validator based annotations. The @Loggable seems to work displaying the time, etc. But the existing TestNG test cases fail at weird code locations. Weird since the @NotNull annotation should not fail because a properly mocked instance of the argument is being passed in the test. I can verify this by removing the ajc plugin from the build->plugins in pom.xml and running the test. Of course, everything works properly.

I am not sure why the MethodValidator of jcabi is being invoked at the stack trace below. Please let me know what I should check. Thanks!!

I am using jcabi-aspects v.0.22.5 and aspectjrt v.1.5.4

**javax.validation.ConstraintViolationException: may not be null**
	at com.jcabi.aspects.aj.MethodValidator.checkForViolations(MethodValidator.java:189)
	at com.jcabi.aspects.aj.MethodValidator.validateMethod(MethodValidator.java:154)
	at com.jcabi.aspects.aj.MethodValidator.beforeMethod(MethodValidator.java:87)
	at ...

I also see this in the logs for init JMockit mocks ...
__________________________________________________
FAILED CONFIGURATION: @BeforeMethod xxx
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Misplaced argument matcher detected here:

-> at ....
You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
Mocking methods declared on non-public parent classes is not supported.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@sandeepkhanzode well, if you pass `NULL` and there is `@NotNull` annotation, you get an exception. That's what jcabi-aspects is doing.

**Comment by naveensharma18** [comment]
I'm not sending null, still getting same exception. Below is the method argument

@NotBlank @FormParam(MOBILE_PHONE_NUMBER) String mobilePhoneNumber
