### ISSUE TITLE
Only able to see method name, not able to see param values, return value

### ISSUE THREAD

**Issue by richard2017spring** [jcabi/jcabi-aspects#240]
I am only able to see method name, not able to see parameters values nor return value. This is probably caused by the error:
Execution default of goal com.jcabi:jcabi-maven-plugin:0.14.1:ajc failed. (com.jcabi:jcabi-maven-plugin:0.14.1:ajc:default:process-classes).

Here is my pom file:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<sonar.exclusions>**/unittest/**</sonar.exclusions>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.0</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.9</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.6.3</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.4</version>
		</dependency>

		<dependency>
  			<groupId>org.slf4j</groupId>
  			<artifactId>slf4j-api</artifactId>
  			<version>1.7.21</version>
		</dependency>
		<dependency>
        	<groupId>org.slf4j</groupId>
           	<artifactId>slf4j-log4j12</artifactId>
         	<version>1.7.21</version>
   		</dependency>
    	<dependency>
      		<groupId>log4j</groupId>
     		<artifactId>log4j</artifactId>
            <version>1.2.17</version>
     	</dependency>

		<dependency>
  			<groupId>org.aspectj</groupId>
  			<artifactId>aspectjrt</artifactId>
  			<version>1.8.10</version>
		</dependency>
		<dependency>
  			<groupId>com.jcabi</groupId>
  			<artifactId>jcabi-aspects</artifactId>
  			<version>0.22.6</version>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.groupId}.${project.artifactId}.${project.version}</finalName>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>com.jcabi</groupId>
					<artifactId>jcabi-maven-plugin</artifactId>
					<version>0.14.1</version>
					<configuration>
						<source>1.7</source>
						<target>1.7</target>
					</configuration>
					<executions>
						<execution>
							<goals>
								<goal>ajc</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
      				<groupId>org.eclipse.m2e</groupId>
      				<artifactId>lifecycle-mapping</artifactId>
      				<version>1.0.0</version>
      				<configuration>
        				<lifecycleMappingMetadata>
          					<pluginExecutions>
            					<pluginExecution>
              						<pluginExecutionFilter>
                						<groupId>com.jcabi</groupId>
                						<artifactId>jcabi-maven-plugin</artifactId>
                						<versionRange>[0.0,)</versionRange>
                						<goals>
                  							<goal>ajc</goal>
                						</goals>
              						</pluginExecutionFilter>
              						<action>
                						<execute />
              						</action>
            					</pluginExecution>
          					</pluginExecutions>
        				</lifecycleMappingMetadata>
      				</configuration>
    			</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
      		<plugin>
        	<groupId>com.jcabi</groupId>
        	<artifactId>jcabi-maven-plugin</artifactId>
        	<version>0.14.1</version>
        	<executions>
          		<execution>
            		<goals>
              			<goal>ajc</goal>
            		</goals>
          		</execution>
        	</executions>
        </plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<finalName>${project.groupId}.${project.artifactId}.${project.version}</finalName>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						 <!-- this is used for inheritance merges	 --> 
						<phase>package</phase>
						 <!-- bind to the packaging phase			 --> 
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.10.4</version>
				<configuration>
					<downloadSources>true</downloadSources>
					<downloadJavadocs>true</downloadJavadocs>
				</configuration>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.5.1</version>
				<configuration>
					<debug>true</debug>
					<debugLevel>vars</debugLevel>
					<compilerArgument>-g:vars</compilerArgument>
					<testCompilerArgument>-g:vars</testCompilerArgument>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

A red line is always show under <execution>

My code is:

```
@Loggable<Loggable.INFO)
public String myMethod(String param){}
```

Could anyone help to see what I did wrong please?
Thanks,

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by richard2017spring** [comment]
In the pom file, under the execution tag, there is a red line with error, and the stacktrace is:

Execution default of goal com.jcabi:jcabi-maven-plugin:0.14.1:ajc failed. (com.jcabi:jcabi-maven-plugin:0.14.1:ajc:default:process-classes)

org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.jcabi:jcabi-maven-plugin:0.14.1:ajc failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:402)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:556)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:534)
	at org.eclipse.core.internal.resources.Project.build(Project.java:111)
	at org.eclipse.jst.common.project.facet.core.internal.JavaFacetUtil$1.run(JavaFacetUtil.java:131)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at com.jcabi.maven.plugin.AjcMojo.dependencies(AjcMojo.java:403)
	at com.jcabi.maven.plugin.AjcMojo.classpath_aroundBody6(AjcMojo.java:380)
	at com.jcabi.maven.plugin.AjcMojo$AjcClosure7.run(AjcMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.jcabi.maven.plugin.AjcMojo.classpath_aroundBody8(AjcMojo.java:357)
	at com.jcabi.maven.plugin.AjcMojo$AjcClosure9.run(AjcMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)
	at com.jcabi.maven.plugin.AjcMojo.classpath(AjcMojo.java:357)
	at com.jcabi.maven.plugin.AjcMojo.executeAJC(AjcMojo.java:285)
	at com.jcabi.maven.plugin.AjcMojo.execute_aroundBody2(AjcMojo.java:264)
	at com.jcabi.maven.plugin.AjcMojo$AjcClosure3.run(AjcMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.jcabi.maven.plugin.AjcMojo.execute_aroundBody4(AjcMojo.java:245)
	at com.jcabi.maven.plugin.AjcMojo$AjcClosure5.run(AjcMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.jcabi.maven.plugin.AjcMojo.execute(AjcMojo.java:245)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 34 more

**Comment by yegor256** [comment]
@richard2017spring thanks for reporting, this definitely looks wrong:

```
Caused by: java.lang.NullPointerException
	at com.jcabi.maven.plugin.AjcMojo.dependencies(AjcMojo.java:403)
```

**Comment by yegor256** [comment]
@richard2017spring but this issue belongs to the jcabi-maven-plugin. Can you please post it here: https://github.com/jcabi/jcabi-maven-plugin/issues
