### ISSUE TITLE
jcabi-aspects version for validation 1.0.0

### ISSUE THREAD

**Issue by mkiran18** [jcabi/jcabi-aspects#250]
Hi , is there a version of jcabi-aspects that is compatible for valiadtion 1.0.0 , jboss EAP 6.4 still uses 1.0 version.

Thanks

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@mkiran18 I believe the current version is compatible with validation 1.0.0. Do you see any errors?

**Comment by mkiran18** [comment]
Hi ,
Apologies for getting back late, 
Below is the error:  @NotNull is used on the getter

JBWEB000236: Servlet.service() for servlet dispatcherServlet threw exception: javax.validation.ValidationException: HV000090: Unable to access getABC.
--
620 | at org.hibernate.validator.internal.util.ReflectionHelper.getValue(ReflectionHelper.java:194)
621 | at org.hibernate.validator.internal.engine.ValidatorImpl.getValue(ValidatorImpl.java:1323)
622 | at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:461)
623 | at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:406)
624 | at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:370)
625 | at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:322)
626 | at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:152)
627 | at org.springframework.validation.beanvalidation.SpringValidatorAdapter.validate(SpringValidatorAdapter.java:110)
628 | at org.springframework.validation.DataBinder.validate(DataBinder.java:891)
629 | at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.validateIfApplicable(AbstractMessageConverterMethodArgumentResolver.java:270)
630 | at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133)
631 | at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
632 | at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:158)
633 | at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:128)
634 | at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
635 | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
636 | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
637 | at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
638 | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
639 | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
640 | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
641 | at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
642 | at javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
643 | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
644 | at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
645 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
646 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
647 | at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
648 | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
649 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
650 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
651 | at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
652 | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
653 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
654 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
655 | at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
656 | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
657 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
658 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
659 | at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
660 | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
661 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
662 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
663 | at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
664 | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
665 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
666 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
667 | at org.springframework.cloud.sleuth.instrument.web.TraceFilter.doFilter(TraceFilter.java:153)
668 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
669 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
670 | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
671 | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
672 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
673 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
674 | at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
675 | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
676 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
677 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
678 | at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
679 | at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
680 | at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
681 | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
682 | at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
683 | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
684 | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
685 | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
686 | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
687 | at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
688 | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150)
689 | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
690 | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
691 | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
692 | at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854)
693 | at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
694 | at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)
695 | at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_91]
696 | Caused by: java.lang.reflect.InvocationTargetException
697 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_91]
698 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_91]
699 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_91]
700 | at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_91]
701 | at org.hibernate.validator.internal.util.ReflectionHelper.getValue(ReflectionHelper.java:188)
702 | ... 75 more
703 | Caused by: java.lang.NoSuchMethodError: javax.validation.Validator.forExecutables()Ljavax/validation/executable/ExecutableValidator;
704 | at com.jcabi.aspects.aj.MethodValidator.after(MethodValidator.java:137)
705 | at getABC(ABC.java:46)
706 | ... 80 more

**Comment by mkiran18** [comment]
just check the javadoc, the method is only added in 1.1

```
forExecutables
ExecutableValidator forExecutables()
Returns the contract for validating parameters and return values of methods and constructors.
Returns:
contract for method and constructor validation
Since:
**1.1**
```
