### ISSUE TITLE
ClassFormatException: Invalid byte tag in constant pool: 19

### ISSUE THREAD

**Issue by imcaizheng** [jcabi/jcabi-aspects#257]
I followed this example http://plugin.jcabi.com/example-java8.html
but encountered some errors as #124.

Here's the error output:
<details>
  <summary><i><b>click to expand...</b></i></summary>
  <pre>
    <code>
      [INFO] --- jcabi-maven-plugin:1.0-SNAPSHOT:ajc (default) @ my-app ---
      [INFO] jcabi-aspects 0.22.6/3f0a1f7 started new daemon thread jcabi-loggable for watching of @Loggable annotated meth
      ods
      [INFO] Unwoven classes will be copied to /home/aaron/my-app/target/unwoven
      [INFO] jcabi-aspects 0.22.6/3f0a1f7 started new daemon thread jcabi-cacheable-clean for automated cleaning of expired
      @Cacheable values
      [INFO] jcabi-aspects 0.22.6/3f0a1f7 started new daemon thread jcabi-cacheable-update for async update of expired @Cac
      heable values
      org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
      at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:139)
      at org.aspectj.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:98)
        at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:186)
        at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
        at org.aspectj.weaver.bcel.BcelWeaver.addAspectsFromJarFile(BcelWeaver.java:260)
        at org.aspectj.weaver.bcel.BcelWeaver.addLibraryJarFile(BcelWeaver.java:236)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:874)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:249)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:185)
        at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
        at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
        at org.aspectj.tools.ajc.Main.run(Main.java:371)
        at com.jcabi.maven.plugin.AjcMojo.executeAJC(AjcMojo.java:285)
        at com.jcabi.maven.plugin.AjcMojo.execute_aroundBody2(AjcMojo.java:264)
        at com.jcabi.maven.plugin.AjcMojo$AjcClosure3.run(AjcMojo.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspec
        ts_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:169)
        at com.jcabi.maven.plugin.AjcMojo.execute_aroundBody4(AjcMojo.java:245)
        at com.jcabi.maven.plugin.AjcMojo$AjcClosure5.run(AjcMojo.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:138)
        at com.jcabi.maven.plugin.AjcMojo.execute(AjcMojo.java:245)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuild
        er.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        Feb 01, 2018 1:50:14 PM org.aspectj.weaver.tools.Jdk14Trace info
      </code>
    </pre>
  </details>
<br>

My `mvn --version`:
>> Apache Maven 3.5.0
>> Maven home: /usr/share/maven
>> Java version: 1.8.0_161, vendor: Oracle Corporation
>> Java home: /usr/lib/jvm/java-8-oracle/jre
>> Default locale: en_HK, platform encoding: UTF-8
>> OS name: "linux", version: "4.13.0-32-generic", arch: "amd64", family: "unix"

And the jcabi plugin in my `pom.xml`:
<details>
  <summary><i><b>click to expand...</b></i></summary>
  <pre>
    <code>
      &lt;plugin&gt;
        &lt;groupId&gt;com.jcabi&lt;/groupId&gt;
        &lt;artifactId&gt;jcabi-maven-plugin&lt;/artifactId&gt;
        &lt;version&gt;0.14.1&lt;/version&gt;
        &lt;executions&gt;
          &lt;execution&gt;
            &lt;configuration&gt;
              &lt;source&gt;1.8&lt;/source&gt;
              &lt;target&gt;1.8&lt;/target&gt;
            &lt;/configuration&gt;
            &lt;goals&gt;
              &lt;goal&gt;ajc&lt;/goal&gt;
            &lt;/goals&gt;
          &lt;/execution&gt;
        &lt;/executions&gt;
        &lt;dependencies&gt;
          &lt;dependency&gt;
            &lt;groupId&gt;com.jcabi&lt;/groupId&gt;
            &lt;artifactId&gt;jcabi-aspects&lt;/artifactId&gt;
            &lt;version&gt;0.22.6&lt;/version&gt;
          &lt;/dependency&gt;
          &lt;dependency&gt;
            &lt;groupId&gt;org.aspectj&lt;/groupId&gt;
            &lt;artifactId&gt;aspectjrt&lt;/artifactId&gt;
            &lt;version&gt;1.8.13&lt;/version&gt;
          &lt;/dependency&gt;
          &lt;dependency&gt;
            &lt;groupId&gt;org.aspectj&lt;/groupId&gt;
            &lt;artifactId&gt;aspectjtools&lt;/artifactId&gt;
            &lt;version&gt;1.8.13&lt;/version&gt;
          &lt;/dependency&gt;
          &lt;dependency&gt;
            &lt;groupId&gt;org.hibernate&lt;/groupId&gt;
            &lt;artifactId&gt;hibernate-validator&lt;/artifactId&gt;
            &lt;version&gt;5.0.0.Final&lt;/version&gt;
            &lt;scope&gt;runtime&lt;/scope&gt;
          &lt;/dependency&gt;
        &lt;/dependencies&gt;
      &lt;/plugin&gt;
    </code>
  </pre>
</details>
<br>

I'm fairly new to Maven and have no idea how to troubleshoot it myself.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by lurodrig** [comment]
Hello there,

I have the same issue when I try to use slf4j-log4j. My dependencies looks like this:

```
    <dependencies>
        <dependency>
            <groupId>com.jcabi</groupId>
            <artifactId>jcabi-aspects</artifactId>
            <version>0.22.6</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>1.8.13</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.10.0</version>
        </dependency>
    </dependencies>
```
With above ones I get `org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19` when the **ajc goal** runs: ` --- jcabi-maven-plugin:0.14.1:ajc`

In the other hand if I used the good and old **java.util.logging** (aka juli) framework it works!

```
22-Feb-2018 16:51:03.534 INFO [main] com.jcabi.log.Logger.info jcabi-aspects 0.22.6/3f0a1f7 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
22-Feb-2018 16:51:03.544 INFO [main] com.jcabi.log.Logger.info #init('ApplicationFilterConfig[name=SsoFilter, filterClass=sso.sp.http.decorator.SsoFilter]'): in 1.48ms
```

However with juli I am falling on this issue:[Wrong Class Name Logged]( https://github.com/jcabi/jcabi-aspects/issues/156)

```
22-Feb-2018 16:51:20.576 INFO [http-nio-8080-exec-1] com.jcabi.log.Logger.info #doFilter(...): entered
22-Feb-2018 16:51:20.581 INFO [http-nio-8080-exec-1] com.jcabi.log.Logger.info #doFilter(...): in 4.73ms
```

Cheers,

Luis

**Comment by Yugen42** [comment]
Same issue here.

**Comment by bernieatenovlab** [comment]
We are also getting the same error and `@Loggable` stopped producing output!

```
org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:139)
	at org.aspectj.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:98)
	at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:186)
	at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
	at org.aspectj.weaver.bcel.BcelWeaver.addAspectsFromJarFile(BcelWeaver.java:260)
	at org.aspectj.weaver.bcel.BcelWeaver.addLibraryJarFile(BcelWeaver.java:236)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:874)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:249)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:185)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at com.jcabi.maven.plugin.AjcMojo.executeAJC(AjcMojo.java:285)
	at com.jcabi.maven.plugin.AjcMojo.execute_aroundBody2(AjcMojo.java:264)
	at com.jcabi.maven.plugin.AjcMojo$AjcClosure3.run(AjcMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.jcabi.maven.plugin.AjcMojo.execute_aroundBody4(AjcMojo.java:245)
	at com.jcabi.maven.plugin.AjcMojo$AjcClosure5.run(AjcMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.jcabi.maven.plugin.AjcMojo.execute(AjcMojo.java:245)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Apr 04, 2018 4:49:02 PM org.aspectj.weaver.tools.Jdk14Trace info
INFO: Dumping to C:\code\backend\.\ajcore.20180404.164902.377.txt

1 fail|abort, 8 warnings
[INFO] ajc result: 792 file(s) processed, 0 pointcut(s) woven, 0 error(s), 0 warning(s)
```

**Comment by GUOMN** [comment]
i have the same issue when using jdk1.8&tomcat 7.0.68...
but it going worked when i using jdk1.8&tomcat8.5.30..

**Comment by bernieatenovlab** [comment]
After some trial and error, I was able to fix the "Invalid byte tag in constant pool: 19" issue by changing the way the plugin is declared, forcing it to use a newer version of AspectJ. The plugin is fairly old by now and uses outdated AspectJ libraries.

```
            <plugin>
                <groupId>com.jcabi</groupId>
                <artifactId>jcabi-maven-plugin</artifactId>
                <version>0.14.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>ajc</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjtools</artifactId>
                        <version>1.9.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>1.9.1</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by yegor256** [comment]
@bernieatenovlab maybe you can contribute with a pull request, to update the dependencies. I will release a new version then.

**Comment by dstcnd11** [comment]
I am running into the same issue. 
Looks like there is a Pull Request with a fix but it's just sitting there.
Is there any blocker? Is there anything others (including myself) can help with to get this resolved for everyone?

**Comment by angiwit** [comment]
I am running into the same issue and i have resolved it. The exception stack trace like below.

Caused by: org.aspectj.apache.bcel.classfile.ClassFormatException: File: 'com.zhongan.hq.gw.anlink.core.AnLinkClient': Invalid byte tag in constant pool: 18
        at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:192)
        at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
        at org.aspectj.apache.bcel.util.NonCachingClassLoaderRepository.loadJavaClass(NonCachingClassLoaderRepository.java:262)
        at org.aspectj.apache.bcel.util.NonCachingClassLoaderRepository.loadClass(NonCachingClassLoaderRepository.java:242)
        at org.aspectj.apache.bcel.util.NonCachingClassLoaderRepository.loadClass(NonCachingClassLoaderRepository.java:249)
        at org.aspectj.weaver.reflect.Java15AnnotationFinder.getAnnotations(Java15AnnotationFinder.java:253)
        at org.aspectj.weaver.reflect.Java15ReflectionBasedReferenceTypeDelegate.getAnnotationTypes(Java15ReflectionBasedReferenceTypeDelegate.java:91)
        at org.aspectj.weaver.reflect.Java15ReflectionBasedReferenceTypeDelegate.hasAnnotation(Java15ReflectionBasedReferenceTypeDelegate.java:98)
        at org.aspectj.weaver.ReferenceType.hasAnnotation(ReferenceType.java:174)
        at org.aspectj.weaver.patterns.ExactAnnotationTypePattern.fastMatches(ExactAnnotationTypePattern.java:85)
        at org.aspectj.weaver.patterns.WithinAnnotationPointcut.fastMatch(WithinAnnotationPointcut.java:85)
        at org.aspectj.weaver.patterns.OrPointcut.fastMatch(OrPointcut.java:46)
        at org.aspectj.weaver.patterns.AndPointcut.fastMatch(AndPointcut.java:47)
        at org.aspectj.weaver.internal.tools.PointcutExpressionImpl.couldMatchJoinPointsInType(PointcutExpressionImpl.java:82)
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.matches(AspectJExpressionPointcut.java:250)
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:220)
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:279)
        at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:311)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:118)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:88)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:69)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:347)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1588)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        ... 36 common frames omitted

as you can see, the first line of the exception stack is something about " org.aspectj", so i checked my pom.xml and found that the aspectj's version was jdk1.6, then i upgraded it to the newest version 1.9x,include 'aspectjweaver' and 'aspectjrt' and this problem was solved. I dont konw wether this is the root reason but it works for me. ps, my english is not good and this is the first time i answer question on github, i hope you can understand me and i hope this would be helpful.

**Comment by Ghilteras** [comment]
Manually adding

```<dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjtools</artifactId>
                        <version>1.9.2</version>
                    </dependency>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>1.9.2</version>
                    </dependency>```

to my `pom.xml` fixes this. I even tried the cutting edge version of `jcabi-maven-plugin` version `1.0-SNAPSHOT` but the problem is still there. Looks like this plugin really needs to be updated

**Comment by e5pe** [comment]
I can't make it work, I thought it was my version (I was using Java 11) but using Java 8 doesn't work either.
It shows an error in the *tag* execution:
`Plugin execution not covered by lifecycle configuration: com.jcabi:jcabi-maven-plugin:0.14.1:ajc (execution: default, phase: process-classes)`

And this is what I added to the pom.xml:
```xml
<plugin>
                <groupId>com.jcabi</groupId>
                <artifactId>jcabi-maven-plugin</artifactId>
                <version>0.14.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>ajc</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <!-- https://mvnrepository.com/artifact/org.aspectj/aspectjtools -->
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjtools</artifactId>
                        <version>1.9.2</version>
                    </dependency>
                    <!-- https://mvnrepository.com/artifact/org.aspectj/aspectjweaver -->
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>1.9.2</version>
                    </dependency>
                </dependencies>
            </plugin>
```
My error is the same that in the title:
**ClassFormatException: Invalid byte tag in constant pool: 19**.
So, any advice? Thank you.

**Comment by aksh1618** [comment]
Adding these in pom.xml works as of today in a Spring Boot 2.5.5 application with Java 11 (Using `@Loggable` with lombok's `@Slf4j`)
```
    <dependencies>
        <dependency>
            <groupId>com.jcabi</groupId>
            <artifactId>jcabi-aspects</artifactId>
            <version>0.23.2</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>1.9.7</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.jcabi</groupId>
                <artifactId>jcabi-maven-plugin</artifactId>
                <version>0.14.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>ajc</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjtools</artifactId>
                        <version>1.9.7</version>
                    </dependency>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>1.9.7</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```

**Comment by yegor256** [comment]
@lurodrig should work now, try latest version 0.24.1
